name: Artifacts
on: [push]

env:
  ARTIFACT_NAME: my_artifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
          - name: Check out the code
            uses: actions/checkout@v2

          - name: upload the artifact
            uses: actions/upload-artifact@v2
            with:
              name: ${{ env.ARTIFACT_NAME }}
              path: .
